<?xml version="1.0"?>
<package format="2">
  <name>test_pkg</name>
  <version>0.0.0</version>
  <description>Test package</description>
  <maintainer email="oguz@example.com">Oguz</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>tf</build_depend>
  <exec_depend>tf</exec_depend>

  <!-- Diğer bağımlılıklarınız varsa buraya ekleyin -->
</package> 